function [out1,out2] = fwd_polar(thetaL,thetaR)
%FWD_POLAR
%    [OUT1,OUT2] = FWD_POLAR(thetaL,thetaR)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    21-May-2025 11:36:02

t2 = cos(thetaL);
t3 = cos(thetaR);
t4 = sin(thetaL);
t5 = sin(thetaR);
t6 = real(t2);
t7 = real(t3);
t8 = real(t4);
t9 = real(t5);
t10 = t2./8.0;
t11 = t3./8.0;
t12 = t2./1.6e+1;
t13 = t3./1.6e+1;
t14 = t4./8.0;
t15 = t5./8.0;
t16 = -t10;
t17 = -t15;
t18 = t6./1.6e+1;
t19 = t7./1.6e+1;
t20 = t8./1.6e+1;
t21 = t9./1.6e+1;
t24 = t8.*6.25e-2i;
t25 = t9.*6.25e-2i;
t22 = -t18;
t23 = -t20;
t26 = -t24;
t27 = t14+t17;
t29 = t11+t16+1.0./1.0e+1;
t28 = t27.^2;
t30 = t29.^2;
t31 = t28+t30;
t32 = 1.0./t31;
t33 = t32./4.0;
t34 = t33-1.0;
t35 = sqrt(t34);
t36 = t27.*t35;
t39 = t29.*t35;
t37 = real(t36);
t38 = t36./2.0;
t42 = real(t39);
t40 = -t38;
t41 = t37./2.0;
t43 = t42./2.0;
t44 = t42.*5.0e-1i;
t45 = t21+t23+t43;
t46 = t19+t22+t41+1.0./2.0e+1;
t47 = t25+t26+t44+t46;
t48 = abs(t47);
t49 = 1.0./t48;
t50 = t46.*t49.*(3.0./1.0e+2);
t51 = -t50;
out1 = sqrt((t4./1.6e+1+t5./1.6e+1-t39./2.0-t45.*t49.*(3.0./1.0e+2)).^2+(t12+t13+t40+t51).^2);
if nargout > 1
    out2 = atan2(t4./1.6e+1+t5./1.6e+1-t39./2.0-t45.*t49.*(3.0./1.0e+2),t12+t13+t40+t51);
end
end
