function [out1,out2] = fwd_cartesian(thetaL,thetaR)
%FWD_CARTESIAN
%    [OUT1,OUT2] = FWD_CARTESIAN(thetaL,thetaR)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    21-May-2025 11:36:02

t2 = cos(thetaL);
t3 = cos(thetaR);
t4 = sin(thetaL);
t5 = sin(thetaR);
t6 = real(t2);
t7 = real(t3);
t8 = real(t4);
t9 = real(t5);
t10 = t2./8.0;
t11 = t3./8.0;
t12 = t4./8.0;
t13 = t5./8.0;
t14 = -t10;
t15 = -t13;
t16 = t6./1.6e+1;
t17 = t7./1.6e+1;
t19 = t8.*6.25e-2i;
t20 = t9.*6.25e-2i;
t18 = -t16;
t21 = -t19;
t22 = t12+t15;
t24 = t11+t14+1.0./1.0e+1;
t23 = t22.^2;
t25 = t24.^2;
t26 = t23+t25;
t27 = 1.0./t26;
t28 = t27./4.0;
t29 = t28-1.0;
t30 = sqrt(t29);
t31 = t22.*t30;
t33 = t24.*t30;
t32 = real(t31);
t35 = real(t33);
t34 = t32./2.0;
t36 = t35.*5.0e-1i;
t37 = t17+t18+t20+t21+t34+t36+1.0./2.0e+1;
t38 = abs(t37);
t39 = 1.0./t38;
out1 = t2./1.6e+1+t3./1.6e+1-t31./2.0-t39.*(t17+t18+t34+1.0./2.0e+1).*(3.0./1.0e+2);
if nargout > 1
    out2 = t4./1.6e+1+t5./1.6e+1-t33./2.0-t39.*(t8.*(-1.0./1.6e+1)+t9./1.6e+1+t35./2.0).*(3.0./1.0e+2);
end
end
